### ISSUE TITLE
Re-think docs

### ISSUE THREAD

**Issue by mapsam** [mapbox/hpp-skel#14]
I like having docs available, but currently we're recommending something that we've never used before, plus it requires a github page, rather than viewing directly in the repo. We typically just document in the README or in an API.md file for node modules - here are some hpp examples at Mapbox:

* https://github.com/mapbox/earcut.hpp
* https://github.com/mapbox/geometry.hpp

I think we should document like this and **not** recommend using cldoc.

cc @springmeyer @GretaCB @flippmoke

**Comment by springmeyer** [comment]
> I think we should document like this and not recommend using cldoc.

👍  Another example of docs is https://github.com/mapbox/protozero/#documentation, which has a more low-level API and therefore needs more comprehensive docs.

**Comment by mapsam** [comment]
Docs were rethunk, we're writing manually since we don't have a 💯 solution for automatic generation right now. Let's revisit in the future if we start seeing more common workflows other than rewriting.
