### ISSUE TITLE
Enable more usage of clang++ sanitizers

### ISSUE THREAD

**Issue by springmeyer** [mapbox/hpp-skel#16]
We currently test the Address sanitizer (https://github.com/google/sanitizers/wiki/AddressSanitizer) via `clang -fsanitize=address`.

We should also test the `undefined` behavior sanitizer.

Note: Recently I learned that these are compatible (so you can do `-fsanitize=address,undefined`). Other sanitizers like `thread` cannot be combined with `address` in the same build. But `thread` does not matter for us since hpp-skel does not use threads.

TODO:

 - [x] Add `undefined` to https://github.com/mapbox/hpp-skel/blob/38ffeaf0ff9e16cd0af7d96a6eddbb4ce9d4cf1b/.travis.yml#L21
 - [x] Fix any errors that show up
 - [x] Also add `-fno-sanitize-recover=all` so that undefined behavior fails the build on first error like the node-cpp-skel does (https://github.com/mapbox/node-cpp-skel/blob/2c4e2e10ca074e59c45819a9b45641f0603fa59d/.travis.yml#L75)

**Comment by mapsam** [comment]
Adding the different checks UndefinedBehaviorSanitizer is performing here http://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#ubsan-checks - for posterity.

**Comment by mapsam** [comment]
This was added in #17 - closing!
