### ISSUE TITLE
use catch.hpp instead of assert

### ISSUE THREAD

**Issue by mapsam** [mapbox/hpp-skel#23]
Let's use catch.hpp instead of assert, since assert comes with some odd Release/Debug quirks that can make it possible to incorrectly run tests successfully (if the `-DNDEBUG` flag is used).

Catch is on Mason now, so let's use that instead of copying.

cc @springmeyer @GretaCB

**Comment by GretaCB** [comment]
👍 Integrated catch into `gzip` branch, I'll plan to create a PR adding catch to this skel...

> Catch is on Mason now, so let's use that instead of copying.

🎉 
_with_ Mason's integrated version, not separate header.

**Comment by GretaCB** [comment]
Ah nevermind, just seeing https://github.com/mapbox/hpp-skel/pull/20#issuecomment-324378902

**Comment by GretaCB** [comment]
Started PR over at https://github.com/mapbox/hpp-skel/pull/44
