### ISSUE TITLE
Update Google Benchmark

### ISSUE THREAD

**Issue by GretaCB** [mapbox/hpp-skel#61]
[Update](https://github.com/mapbox/hpp-skel/blob/master/CMakeLists.txt#L38) to latest [Google Benchmark](https://github.com/google/benchmark) version `1.3.0`.

Also, at the same time:

 - [ ] Assert the results are expected, to ensure the benchmark is working right
 - [ ] Learn from: https://github.com/mapbox/gzip-hpp/commit/17a2ba8d1f9ffd8d35aa12b8c78b2fce291dfc96#diff-e21ec455a183f748ecfe2b6f5233f589
 - [ ] Learn from https://github.com/mapbox/vector-tile/blob/2.x/bench/run.cpp

**Comment by springmeyer** [comment]
Done in #68.
